apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80          # Port that the service exposes
      targetPort: 3000  # Port on the container to forward to
  type: LoadBalancer     # Type of service (ClusterIP, NodePort, LoadBalancer, ExternalName)
